name: Breno Polanski
description: Blog
meta_description: 'A developer who loves to learn new programming languages​​, build Open Source projects and play video game :)'

github: https://github.com/brenopolanski/

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url: 'http://brenopolanski.com'
author: 'Breno Polanski'
