name: Breno Polanski
description: Front-End Software Engineer at Meteorite BI
meta_description: "Breno Polanski's blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://brenopolanski.com'
google_analytics: 'UA-65891833-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://brenopolanski.com'
author:         'Breno Polanski'
authorTwitter:  'brenopolanski'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
