export const quoteText = {
  en: {
    title: 'Tick-tock. Tick-tock.',
    text: `Time is the most important asset. Time does not equal money. Time equals life. And you only have one chance to make it right. Every human being is fighting a battle inside themselves. It's your obligation to help and inspire them. Regardless of what you do, you can always inspire others to do good. Nobody is better than you. And you're not better than anybody else. Be humble. Being in the comfort zone is wonderful, but nothing ever grows there. Keep studying. Keep creating. Haters will come if you have the audacity to build something new. Don't let them define you. Don't let them stop you. Just block them and keep going. Don't expect others to make you happy. You are the only one responsible for your happiness. Don't wait until friday to enjoy life. Joy should be present in everything you do. Be kind to your parents. They gave up many things for you. Having hundreds of people admiring you is worthless, if you're not admired by your own family. Don't fear the unknown. Fear knowing everything. Life is too damn short and every day counts. Do what you wanna do and do it now. Tick-tock don't stop. Tick-tock don't wait.`,
  },
  'pt-br': {
    title: 'Tique-taque. Tique-taque.',
    text: `Tempo é o ativo mais importante. Tempo não é igual a dinheiro. Tempo é igual a vida. E você só tem uma chance de fazer direito. Todo ser humano está travando uma batalha interior. É sua obrigação ajudar e inspirar. Independentemente do que você faz, você sempre pode inspirar outros a fazer o bem. Ninguém é melhor que você. E você não é melhor que ninguém. Seja humilde. Estar na zona de conforto é maravilhoso, mas nada cresce lá. Continue estudando. Continue criando. Haters virão se você tiver a audácia de construir algo novo. Não deixe que eles te definam. Não deixe que eles te parem. Apenas bloqueie-os e siga em frente. Não espere que outros te façam feliz. Você é o único responsável pela sua felicidade. Não espere até sexta-feira para aproveitar a vida. A alegria deve estar presente em tudo que você faz. Seja gentil com seus pais. Eles abriram mão de muitas coisas por você. Ter centenas de pessoas te admirando não vale nada se você não é admirado pela sua própria família. Não tema o desconhecido. Tema saber tudo. A vida é muito curta e cada dia conta. Faça o que você quer fazer e faça agora. Tique-taque não para. Tique-taque não espera.`,
  },
}
